# Generated by Django 5.0.8 on 2024-09-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_column='gender', max_length=10, null=True),
        ),
    ]
